export const personalInfo = {
	name: "Noah Gaiji",
	location: "Strasbourg, France",
	email: "noah.gaiji@gmail.com",
	cv: "/cv.pdf",
	linkedin: "https://www.linkedin.com/in/noah-gaiji-b58343358/",
	profilePicture: "/profile-picture.jpg",
	heroDescription: [
		"Passionné par la chimie, je me suis orienté vers un master de Chimie moléculaire et supramoléculaire à l’Université de Strasbourg, après avoir obtenu une licence de chimie, parcours international, à l’Université de Bordeaux. J’ai également eu l’opportunité d’effectuer une année à l’étranger à Genève, durant laquelle j’ai suivi la troisième année de mon bachelor.",
		"Ce qui m’a motivé à poursuivre un master de chimie, ce sont les recherches menées sur des structures supramoléculaires fascinantes, notamment les cages métallo supramoléculaires de Fujita, les caténanes de Jean‑Marie Lehn, les rotaxanes de Jean‑Pierre Sauvage, ainsi que les pinces moléculaires.",
		"Souhaitant m’orienter vers la recherche fondamentale, j’envisage une carrière soit comme enseignant-chercheur, soit comme chercheur au sein de structures académiques ou institutionnelles, en France et à l’international. Habitué aux mobilités académiques et géographiques multiples, je m’adapte facilement à de nouveaux contextes et équipes de recherche.",
	],
};

export const workExperience = [
	{
		company: "Coty",
		location: "Monaco 🇲🇨",
		position: "Stage en recherche et développement",
		period: "Juin - Juillet 2025",
		achievements: [
			"Analyse Stabilité Cosmétiques, Tests stabilité de compositions solaires et autres sur différentes périodes de temps à températures variées.",
			"Maîtrise de techniques analytiques : HPLC, UPLC, GC, pH-métrie.",
			"Rédaction de rapports techniques détaillés pour documenter les résultats des tests de stabilité.",
		],
		emblem: "/coty.png",
		emblemShape: "rect",
	},
	{
		company: "Musée Océanographique de Monaco",
		location: "Monaco 🇲🇨",
		position: "Réceptionniste / Guide",
		period: "Été 2023",
		achievements: [
			"Service client, adaptabilité, communication multilingue, résolution de problèmes, travail en équipe, prise de parole en public.",
		],
		emblem: "/musee-oceanographique.png",
		emblemShape: "square",
	},
];

export const education = [
	{
		institution: "Université de Starsbourg",
		location: "Strasbourg, France 🇫🇷",
		degree: "Master 1, Chimie Moléculaire et Supramoléculaire",
		period: "Septembre 2025 - Présent",
		achievements: [
			"J'ai approfondi mes connaissances en chimie supramoléculaire, en étudiant les interactions non covalentes et la conception de structures moléculaires complexes.",
			"Participation à un projet de recherche et de synthèse axé sur la caractérisation, la synthèse, et la formation de MOFs (Metal-Organic Frameworks) pour des applications en stockage de gaz et en catalyse (liguand alloxazine).",
			"Maîtrise de compétences en techniques de laboratoire avancées en physico-chimie.",
		],
		emblem: "uni-strasbourg.png",
		emblemShape: "rect",
	},
	{
		institution: "Université de Genève",
		location: "Genève, Suisse 🇨🇭",
		degree: "Année à l'étranger - Bachelor 3, Chimie",
		period: "Septembre 2024 - Juin 2025",
		achievements: [
			"Au travers des travaux pratiques quotidiens d'après-midi, j'ai développé une autonomie expérimentale polyvalente en chimie organique de synthèses, physique , inorganique et cristallographiques et analytique.",
			"Maîtrise des techniques analytiques : HPLC, GPC/SEC, GC-MS, UPLC, cyclovoltamétrie, UV/Vis, fluorescence, électrophorèse capillaire, chromatographie ionique, RMN, RPE.",
			"Appliqué en chimie physique/inorganique : spectroscopie Raman, spectroscopie électronique, mesures FRET et quenching de fluorescence pour analyser interactions moléculaires et transferts d'énergie.",
			"Cette expertise multidisciplinaire (interprétation spectrale, optimisation protocoles) démontre ma polyvalence pour des projets de recherche.",
		],
		emblem: "/uni-geneve.png",
		emblemShape: "rect",
	},
	{
		institution: "Université de Bordeaux",
		location: "Bordeaux, France 🇫🇷",
		degree: "License de Chimie, Parcours International | Mention Bien",
		period: "Septembre 2022 - Juillet 2025",
		achievements: [
			"J'ai acquis des concepts essentiels dans tous les domaines fondamentaux, consolidant les bases nécessaires à ma progression vers le futur. J'ai maîtrisé les principes de la thermodynamique et des équilibres chimiques. Parallèlement, j'ai approfondi la chimie organique ainsi que la chimie inorganique et des polymères.",
			"Ce parcours m'a rendu bilingue scientifique : l'ensemble des cours théoriques  et travaux pratiques s'est déroulé en anglais.",
			"Cette immersion linguistique a consolidé mes compétences techniques tout en me préparant aux exigences des recherches européens et carrières internationales en chimie.",
		],
		emblem: "/uni-bordeaux.png",
		emblemShape: "rect",
	},
	{
		institution: "Lycée Albert 1er de Monaco",
		location: "Monaco 🇲🇨",
		degree:
			"Baccalauréat Section Européenne - SVT & Physique-Chimie | Mention Très Bien",
		period: "2021",
		emblem: "/lycee-albert-1er.jpeg",
		emblemShape: "square",
	},
];
export const skills = {
	chimieOrga: [
		"Synthèse multi-étapes",
		"Réaction sous atmosphère inerte",
		"Catalyse homogène et hétérogène",
		"Montage à reflux",
		"Extraction liquide-liquide",
		"Filtration sur Büchner et sur frité",
		"Recrystallisation",
		"Distillation fractionnée",
		"Manipulation de produits toxiques, dangereux ou carcinogènes",
		"Rotavaporation",
		"Rampe de Schlenk",
		"Caractérisation (NMR, IR, UV-Vis, Fluorescence)",
		"Manipulation de composés sensibles à l'air et à l'humidité",
		"Chimie des carbonyles",
		"Synthèse totale",
		"Catalyse organométallique",
		"Réaction asymétrique",
		"Réaction péricyclique",
		"Réaction Sigmatropique et Cycloaddition",
		"Chimie bioorganique",
	],
	chimiePhy: [
		"Spectroscopie rotionnelle",
		"Spectroscopie vibrationnelle (harmonique et anharmonique)",
		"Modes normaux polyatomiques",
		"Théorie des groupes (IR / Raman actives)",
		"Spectroscopie électronique (Jablonski)",
		"Photophysique quantiques",
		"Modèles de Lorentz",
		"Fluorescence et phosphorescence",
		"Conversion interne et intersystème",
		"Quenching de fluorescence (Stern-Volmer)",
		"Transfert d'énergie FRET",
		"Règles de selection",
		"Règles de Kasha",
		"RMN avancée",
		"Effet Zeeman",
		"Couplage hyperfin",
		"Couplage dipolaire (Pake pattern)",
		"Couplage de Fermi-contact",
		"Polarisation optique",
		"Dispersion rotatoire",
		"Dichroïsme circulaire",
		"Diffraction Raman rotationnelle",
		"Effet Stark",
	],
	chimieAna: [
		"Spectrométrie de masse (SM)",
		"Interprétation de spectres de masse",
		"Calcul de masse exacte et précision de masse",
		"Détermination de formules élémentaires",
		"Analyse isotopique",
		"Ionisation EI (Impact Électronique)",
		"Ionisation CI (Ionisation Chimique)",
		"Ionisation APCI",
		"Ionisation ESI (Electrospray)",
		"Ionisation MALDI",
		"Analyse de peptides et protéines par SM",
		"Analyseurs quadripolaires",
		"Trappes ioniques (2D et 3D)",
		"Spectrométrie de masse tandem (MS/MS)",
		"Triple quadripôle",
		"Fragmentation CID/CAD",
		"Haute résolution (TOF, Orbitrap, FT-MS)",
		"Calibration et tuning d’instruments SM",
		"Quantification en mode MRM/SRM",
		"Méthodes de calibration avec étalon interne",
		"Analyse LC-MS",
		"Analyse SFC-MS",
		"Acquisition DIA et DDA",
		"Mobilité ionique (DTIMS, DMS)",
		"Imagerie par spectrométrie de masse",
		"HPLC",
		"GPC/SEC",
		"GC-MS",
		"GC",
		"UPLC",
		"Cyclovoltamétrie",
		"UV/Vis",
		"Fluorescence",
		"Électrophorèse capillaire",
		"Chromatographie ionique",
		"RMN",
		"RPE",
	],
	chimieInorga: [
		"Structure électronique des éléments de transition",
		"Description quantique des orbitales atomiques",
		"Nombres quantiques et fonctions d’onde",
		"Configurations électroniques des ions de transition",
		"Répulsion électron–électron",
		"Modèle de l’ion libre",
		"Termes spectroscopiques",
		"Couplage Russell–Saunders",
		"Couplage spin–orbite",
		"Règles de Hund",
		"Calcul et interprétation des niveaux spectroscopiques",
		"Effet du champ cristallin",
		"Théorie du champ cristallin",
		"Théorie du champ des ligands",
		"Éclatement des orbitales d",
		"Diagrammes de corrélation",
		"Diagrammes de Tanabe–Sugano",
		"Analyse haut spin / bas spin",
		"Transitions de spin",
		"Modèle du recouvrement angulaire",
		"Magnétisme moléculaire",
		"Diamagnétisme",
		"Paramagnétisme",
		"Ferromagnétisme et antiferromagnétisme",
		"Mesure des propriétés magnétiques (Gouy, Faraday, SQUID)",
		"Susceptibilité magnétique",
		"Correction diamagnétique",
		"Paramagnétisme indépendant de la température (TIP)",
		"Couplage magnétique",
		"Zero-field splitting",
		"Chimie des complexes",
		"Cristallographie des solides",
		"Analyse des mailles cristallines",
		"Paramètres de maille",
		"Réseaux de Bravais",
		"Groupes spatiaux",
		"Opérations de symétrie cristalline",
		"Symétrie ponctuelle et symétrie d’espace",
		"Propriétés électroniques des solides",
		"Propriétés magnétiques des matériaux",
		"Propriétés structurales et symétrie–propriétés",
	],
	languages: ["Français (natif)", "Anglais (C1)", "Espagnol (B2)"],
};

export const awards = [
	{
		name: "Volleyball",
	},
	{
		name: "Science",
	},
	{
		name: "Jeux Vidéo",
	},
	{
		name: "Musique",
	},
	{
		name: "Voyages",
	},
];
